# .github/workflows/build_executables.yml
name: Build and Release AskQL App

on:
  release:
    types: [published]

env:
  NODE_VERSION: "20"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm cache clean --force && npm install

      - name: Build the app
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            npm run build -- --mac
          else
            npm run build -- --win
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.exe
          retention-days: 14 # Artifacts 보존 기간 설정

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.dmg
            dist/*.exe
